url: 'https://dr-griezel.github.io'
baseurl: ''
title: "The Vault"
subtitle: 'Research notes and build logs'
copyright: 'DR-GRIEZEL, bachjamal-commits44'
exclude:
  - test
  - node_modules
  - coverage
